### ISSUE TITLE
tvtk could not be installed

### ISSUE THREAD

**Issue by OllisGit** [shodushi/gcode2png#1]
Hi @shodushi ,
I was trying to use your tool but without success.
Python 2.7.9
```
 » pip install numpy mayavi tvtk Pillow                                                                                         DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/51/67/8907005262f493e356195bcbd61b41988eecf63cb1d97ea2f6e55fe24205/numpy-1.16.5-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting mayavi
  Using cached https://files.pythonhosted.org/packages/08/ea/eb808cb4df8f92bc4d9f9a1ef14566b9b5d60370e6ecbaf9061cdae335fa/mayavi-4.7.1.tar.bz2
ERROR: Could not find a version that satisfies the requirement tvtk (from versions: none)
ERROR: No matching distribution found for tvtk
```
Do you have any idea how to fix this?

Thx, in advance
Olli

**Comment by shodushi** [comment]
Hi @OllisGit 

I will try to reproduce it, probably I'll try installing on rpi to test. I will post a solution (hopefully)

**Comment by OllisGit** [comment]
Hi @shodushi, I used a MacBookPro with PyCharm and not a RaspberryPI!
I created a venv:
```
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip install numpy mayavi tvtk Pillow 
```

**Comment by shodushi** [comment]
Hi @OllisGit,

I went through my bash history and tried on another MacBook (without virtualenv). The tvtk error was gone after installing following without installing tvtk:

sudo pip install bokeh
sudo pip install matplotlib
sudo pip install numpy mayavi Pillow

Please let me know if it's working for you

**Comment by OllisGit** [comment]
Hi @shodushi ,
thx, for your response!

I started with a fresh ```venv``` on my mac. The installation of the first packages went well, but installing ```mayavi``` result in an error:
```
pip install numpy mayavi Pillow                                                                                                    o0632@Olafs-MBP
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in ./venv3/lib/python2.7/site-packages (1.16.5)
Collecting mayavi
  Using cached https://files.pythonhosted.org/packages/08/ea/eb808cb4df8f92bc4d9f9a1ef14566b9b5d60370e6ecbaf9061cdae335fa/mayavi-4.7.1.tar.bz2
Requirement already satisfied: Pillow in ./venv3/lib/python2.7/site-packages (6.2.1)
Processing /Users/o0632/Library/Caches/pip/wheels/c2/bf/9c/3037e3c4bbd95652aa5844086ecf812f83501ba9e00a4779d8/apptools-4.5.0-cp27-none-any.whl
Processing /Users/o0632/Library/Caches/pip/wheels/70/19/fb/bd7212543e32b02afe11cba36607fae01e342133e44b369407/envisage-4.8.0-cp27-none-any.whl
Processing /Users/o0632/Library/Caches/pip/wheels/99/7c/75/0ce4d816cbcf9da1a2887b5d17a8c7e283a11622e008c8455d/pyface-6.1.2-cp27-none-any.whl
Collecting pygments
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Processing /Users/o0632/Library/Caches/pip/wheels/07/a9/28/7705539d9cb37ef1ef984e0019910071ce1fb5ed60873ca455/traits-5.1.2-cp27-cp27m-macosx_10_14_x86_64.whl
Processing /Users/o0632/Library/Caches/pip/wheels/bb/e3/a6/982d407becc93e50a3732c9374c19741e4779257b753c2d71c/traitsui-6.1.3-cp27-none-any.whl
Collecting vtk
  Using cached https://files.pythonhosted.org/packages/d6/0e/0c91f7b6e7231e46536d163a7101aac38d71e52297570817307cece5985b/vtk-8.1.2-cp27-cp27m-macosx_10_6_x86_64.whl
Requirement already satisfied: six in ./venv3/lib/python2.7/site-packages (from apptools->mayavi) (1.13.0)
Processing /Users/o0632/Library/Caches/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0/configobj-5.0.6-cp27-none-any.whl
Requirement already satisfied: setuptools in ./venv3/lib/python2.7/site-packages (from envisage->mayavi) (41.6.0)
Building wheels for collected packages: mayavi
  Building wheel for mayavi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/setup.py'"'"'; __file__='"'"'/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-wheel-Gq4FT3 --python-tag cp27
       cwd: /private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/
  Complete output (33 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/setup.py", line 474, in <module>
      **config
    File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/o0632/.pyenv/versions/2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Users/o0632/.pyenv/versions/2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Users/o0632/.pyenv/versions/2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Users/o0632/.pyenv/versions/2.7.9/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Users/o0632/.pyenv/versions/2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/setup.py", line 268, in run
      build_tvtk_classes_zip()
    File "/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/setup.py", line 254, in build_tvtk_classes_zip
      gen_tvtk_classes_zip()
    File "tvtk/setup.py", line 83, in gen_tvtk_classes_zip
      from tvtk.code_gen import TVTKGenerator
    File "/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/tvtk/code_gen.py", line 10, in <module>
      import vtk_module as vtk
    File "/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-install-MO0zcB/mayavi/tvtk/vtk_module.py", line 15, in <module>
      from vtk import *
  ImportError: No module named vtk
  ----------------------------------------
  ERROR: Failed building wheel for mayavi
  Running setup.py clean for mayavi
Failed to build mayavi
Installing collected packages: traits, pyface, traitsui, configobj, apptools, envisage, pygments, vtk, mayavi
    Running setup.py install for mayavi ... done
Successfully installed apptools-4.5.0 configobj-5.0.6 envisage-4.8.0 mayavi-4.7.1 pyface-6.1.2 pygments-2.4.2 traits-5.1.2 traitsui-6.1.3 vtk-8.1.2
```

Executing ```gcode2png``` looks like this:
```
python ./gcode2png test.gcode                                                                                                      o0632@Olafs-MBP
Traceback (most recent call last):
  File "./gcode2png", line 202, in <module>
    renderer.run(path, support, moves, bed, show)
  File "./gcode2png", line 65, in run
    self.createScene()
  File "./gcode2png", line 108, in createScene
    fig1 = mlab.figure(bgcolor=(1,1,1),size=(self.imgwidth,self.imgheight))
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/mayavi/tools/figure.py", line 64, in figure
    engine = get_engine()
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 92, in get_engine
    return self.new_engine()
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 137, in new_engine
    check_backend()
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/3rdParty/gcode2png/venv3/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 40, in check_backend
    raise ImportError(msg)
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed.
```

**Comment by shodushi** [comment]
Hi @OllisGit,

I think installing wxPython as an alternative to QT should fix it. At least I have it installed on my Mac

I had to install a lot of packages back in the days to get mayavi working on my Mac, and honestly I lost track of what was really necessary, thats why the installation instructions in README are not really working. I postponed updating the README a bit :-)

Sorry for the inconvenience

I'm glad to help, please let me know if it's working for you, now

**Comment by OllisGit** [comment]
Okay, I successfully installed it:

```
pip install wxPython                                                                                                               o0632@Olafs-MBP
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting wxPython
  Using cached https://files.pythonhosted.org/packages/1c/a5/a308b99771f2c4f22a2641bda378e3e1b38407b34e67f0ac4fe5d0614500/wxPython-4.0.7.post1-cp27-cp27m-macosx_10_9_x86_64.whl
Requirement already satisfied: six in ./venv3/lib/python2.7/site-packages (from wxPython) (1.13.0)
Requirement already satisfied: numpy<1.17; python_version <= "2.7" in ./venv3/lib/python2.7/site-packages (from wxPython) (1.16.5)
Requirement already satisfied: pillow in ./venv3/lib/python2.7/site-packages (from wxPython) (6.2.1)
Installing collected packages: wxPython
Successfully installed wxPython-4.0.7.post1
```
But executing doesn't work:
```
python ./gcode2png test.gcode                                                                                                 
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

What does this mean?

**Comment by shodushi** [comment]
I found on stackoverflow, that it is not working in a virtual environment because things in a virtual environment are isolated from your mac and so can not access the display(manager), which is needed here.

https://stackoverflow.com/a/52732858

So either installing without virtual environment or calling  "pythonw ./gcode2png" should work

I installed it directly, so therefor I did not ran into this error

So close :-)

**Comment by OllisGit** [comment]
Hi,

didn't work!
- I deactivated the venv
- Installed the packages on the real python 2.7 without an error!
- Executing:
```
pythonw ./gcode2png test.gcode                                                                                                     
Traceback (most recent call last):
  File "./gcode2png", line 6, in <module>
    from mayavi import mlab
  File "/Library/Python/2.7/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/Library/Python/2.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/Library/Python/2.7/site-packages/mayavi/tools/engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "/Library/Python/2.7/site-packages/mayavi/preferences/api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "/Library/Python/2.7/site-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "/Library/Python/2.7/site-packages/traitsui/api.py", line 27, in <module>
    from .basic_editor_factory import BasicEditorFactory
  File "/Library/Python/2.7/site-packages/traitsui/basic_editor_factory.py", line 30, in <module>
    from .editor_factory import EditorFactory
  File "/Library/Python/2.7/site-packages/traitsui/editor_factory.py", line 37, in <module>
    from .toolkit import toolkit_object
  File "/Library/Python/2.7/site-packages/traitsui/toolkit.py", line 113, in <module>
    class Toolkit(Toolkit):
  File "/Library/Python/2.7/site-packages/traits/has_traits.py", line 489, in __new__
    class_name, bases, class_dict, is_category=False
  File "/Library/Python/2.7/site-packages/traits/has_traits.py", line 750, in update_traits_class_dict
    view_elements.parents.append(parent_view_elements)
  File "/Library/Python/2.7/site-packages/traits/trait_handlers.py", line 2661, in append
    value = validate(object, self.name, value)
  File "/Library/Python/2.7/site-packages/traits/trait_handlers.py", line 1449, in validate
    from traits.adaptation.api import adapt
  File "/Library/Python/2.7/site-packages/traits/adaptation/api.py", line 18, in <module>
    from .adaptation_offer import AdaptationOffer
  File "/Library/Python/2.7/site-packages/traits/adaptation/adaptation_offer.py", line 19, in <module>
    from traits.util.api import import_symbol
  File "/Library/Python/2.7/site-packages/traits/util/api.py", line 4, in <module>
    from .event_tracer import record_events
  File "/Library/Python/2.7/site-packages/traits/util/event_tracer.py", line 40, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

hmmm...my idea was to use this lib in one of my OctoPrint plugins to create images from gcode. I think with such dependencies Octoprint is not running.

Thanks a lot for your support!
Olli

**Comment by shodushi** [comment]
Hmm, thats strange I will investigate this further...
